// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repositories

import (
	"context"
)

type Querier interface {
	CountUser(ctx context.Context) (int32, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	FindUser(ctx context.Context, arg *FindUserParams) ([]*User, error)
}

var _ Querier = (*Queries)(nil)
