// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package repositories

import (
	"context"
)

const countUser = `-- name: CountUser :one
SELECT COUNT(*)::int4
FROM users
`

func (q *Queries) CountUser(ctx context.Context) (int32, error) {
	row := q.queryRow(ctx, q.countUserStmt, countUser)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password)
VALUES ($1, $2)
RETURNING id, username, password, created_at, updated_at
`

type CreateUserParams struct {
	Username string `db:"username" json:"username"`
	Password string `db:"password" json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findOneUserByUsername = `-- name: FindOneUserByUsername :one
SELECT id, username, password, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) FindOneUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.queryRow(ctx, q.findOneUserByUsernameStmt, findOneUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const findUser = `-- name: FindUser :many
SELECT id, username, password, created_at, updated_at
FROM users
LIMIT $2
OFFSET $1
`

type FindUserParams struct {
	Offset int32 `db:"offset" json:"offset"`
	Limit  int32 `db:"limit" json:"limit"`
}

func (q *Queries) FindUser(ctx context.Context, arg *FindUserParams) ([]*User, error) {
	rows, err := q.query(ctx, q.findUserStmt, findUser, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
